name: Bug report
description: File a bug report
title: '[BUG]'
labels: bug

body:
  - type: textarea
    id: bug-report
    attributes:
      label: Issue description
      description: |
        Description of the issue - include code snippets and screenshots here if relevant. You may use the following template.
      placeholder: Tell us what you see!
      value: |
        * *Expected behavior:* (What you expect to happen)
        |
        * *Actual behavior:* (What actually happens)
        |
        * *Reproduces how often:* (What percentage of the time does it reproduce?)
        |
        * *System information:* (Post the output of `import pennylane as qml; qml.about()`)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Source code and tracebacks
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: info
    attributes:
      label: Additional information
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Before posting a bug report
      description: |
        Search existing GitHub issues to make sure the issue does not already exist:
        https://github.com/xanaduai/pennylane/issues
        |
        For general technical details check out our documentation:
        https://pennylane.readthedocs.io
      options:
        - label: I have searched exisisting issues.
          required: true
