name: Bug report
description: File a bug report
title: '[BUG]'
labels: bug

body:
  - type: markdown
    id: description
    attributes:
      value: |
          # Before posting a bug report
          Search existing GitHub issues to make sure the issue does not already exist:
          https://github.com/xanaduai/pennylane/issues
          
          For general technical details check out our documentation:
          https://pennylane.readthedocs.io
  - type: textarea
    id: expected
    attributes:
      label: Issue description
      description: |
        Description of the issue - include code snippets and screenshots here if relevant. You may use the following template.
      value: |
        * *Expected behavior:* (What you expect to happen)

        * *Actual behavior:* (What actually happens)

        * *Reproduces how often:* (What percentage of the time does it reproduce?)

        * *System information:* (Post the output of `import pennylane as qml; qml.about()`)
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: info
      description: |
        Any additional information, configuration or data that might be necessary to reproduce the issue.
  - type: textarea
    id: logs
    attributes:
      label: Source code and tracebacks
      description: Please include any additional code snippets and error tracebacks related to the issue here. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      options:
        - label: I have searched exisisting GitHub issues to make sure the issue does not already exist.
          required: true
